"""create_mvp1_tables

Revision ID: 32b4ad6f6514
Revises: 7314efbbfe73
Create Date: 2026-06-25 02:54:21.758503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b4ad6f6514'
down_revision: Union[str, Sequence[str], None] = '7314efbbfe73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('completed_runs', sa.Integer(), nullable=False),
    sa.Column('failed_runs', sa.Integer(), nullable=False),
    sa.Column('max_parallel', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manifests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('manifest_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('manifest_version', sa.String(length=50), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'kind', 'manifest_id', name='uq_manifests_tenant_kind_id')
    )
    op.create_table('runspecs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('snapshots', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_refs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_value', sa.String(), nullable=False),
    sa.Column('key_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_secret_refs_tenant_name')
    )
    op.create_table('tool_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('runspec_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['runspec_id'], ['runspecs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['tool_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('raw_result_id', sa.String(), nullable=False),
    sa.Column('normalization_status', sa.String(length=50), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('metrics_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raw_result_id'], ['raw_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['tool_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('normalized_result_id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(length=255), nullable=False),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('expected_output', sa.String(), nullable=True),
    sa.Column('output_text', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_sample_ref', sa.String(length=500), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['normalized_result_id'], ['normalized_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Indexes for tool_runs
    op.create_index('ix_tool_runs_tenant_id_status', 'tool_runs', ['tenant_id', 'status'])
    op.create_index('ix_tool_runs_tenant_id_created_at', 'tool_runs', ['tenant_id', 'created_at'])

    # Indexes for normalized_results
    op.create_index('ix_normalized_results_run_id', 'normalized_results', ['run_id'])
    op.create_index('ix_normalized_results_tenant_id_created_at', 'normalized_results', ['tenant_id', 'created_at'])

    # Indexes for normalized_samples
    op.create_index('ix_normalized_samples_normalized_result_id', 'normalized_samples', ['normalized_result_id'])
    op.create_index('ix_normalized_samples_tenant_id_status', 'normalized_samples', ['tenant_id', 'status'])

    # Indexes for raw_results
    op.create_index('ix_raw_results_run_id', 'raw_results', ['run_id'])
    op.create_index('ix_raw_results_tenant_id_storage_status', 'raw_results', ['tenant_id', 'storage_status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_results_tenant_id_storage_status', table_name='raw_results')
    op.drop_index('ix_raw_results_run_id', table_name='raw_results')
    op.drop_index('ix_normalized_samples_tenant_id_status', table_name='normalized_samples')
    op.drop_index('ix_normalized_samples_normalized_result_id', table_name='normalized_samples')
    op.drop_index('ix_normalized_results_tenant_id_created_at', table_name='normalized_results')
    op.drop_index('ix_normalized_results_run_id', table_name='normalized_results')
    op.drop_index('ix_tool_runs_tenant_id_created_at', table_name='tool_runs')
    op.drop_index('ix_tool_runs_tenant_id_status', table_name='tool_runs')

    op.drop_table('normalized_samples')
    op.drop_table('normalized_results')
    op.drop_table('raw_results')
    op.drop_table('tool_runs')
    op.drop_table('secret_refs')
    op.drop_table('runspecs')
    op.drop_table('manifests')
    op.drop_table('batches')
    # ### end Alembic commands ###
