"""create_mvp2_tables

Revision ID: 38278e786739
Revises: 32b4ad6f6514
Create Date: 2026-06-25 03:02:30.272370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38278e786739'
down_revision: Union[str, Sequence[str], None] = '32b4ad6f6514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_actor_tenant', 'audit_events', ['actor_id', 'tenant_id'], unique=False)
    op.create_index('ix_audit_events_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_events_tenant_id_timestamp', 'audit_events', ['tenant_id', 'timestamp'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metrics_delta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comparisons_tenant_id_created_at', 'comparisons', ['tenant_id', 'created_at'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'tenant_id')
    )
    op.create_table('tenant_quotas',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('max_concurrent_runs', sa.Integer(), nullable=False),
    sa.Column('max_monthly_runs', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('tenant_retention_configs',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('raw_results_retention_days', sa.Integer(), nullable=False),
    sa.Column('reports_retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('comparison_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('comparison_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['tool_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['tool_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_events_run_id_created_at', 'run_events', ['run_id', 'created_at'], unique=False)
    # RLS Enforcement for PostgreSQL (Gate 22)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        tenant_tables = [
            'manifests', 'runspecs', 'tool_runs', 'raw_results',
            'normalized_results', 'normalized_samples', 'comparisons',
            'api_keys', 'audit_events', 'idempotency_keys'
        ]
        for t in tenant_tables:
            op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;")
            op.execute(f"CREATE POLICY tenant_isolation_policy ON {t} USING (tenant_id = current_setting('app.current_tenant_id', true));")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        tenant_tables = [
            'manifests', 'runspecs', 'tool_runs', 'raw_results',
            'normalized_results', 'normalized_samples', 'comparisons',
            'api_keys', 'audit_events', 'idempotency_keys'
        ]
        for t in tenant_tables:
            op.execute(f"DROP POLICY IF EXISTS tenant_isolation_policy ON {t};")
            op.execute(f"ALTER TABLE {t} DISABLE ROW LEVEL SECURITY;")
            
    op.drop_index('ix_run_events_run_id_created_at', table_name='run_events')
    op.drop_table('run_events')
    op.drop_table('comparison_items')
    op.drop_table('tenant_retention_configs')
    op.drop_table('tenant_quotas')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_comparisons_tenant_id_created_at', table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index('ix_audit_events_tenant_id_timestamp', table_name='audit_events')
    op.drop_index('ix_audit_events_resource', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_tenant', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
